In [1]:
import numpy as np

# 1D Array
a = np.array([1, 2, 3, 4, 5])

print('Array:', a)
print('Shape:', a.shape)
print('Size:', a.size)
print('Data type:', a.dtype)
print('Number of dimensions:', a.ndim)

Array: [1 2 3 4 5]
Shape: (5,)
Size: 5
Data type: int64
Number of dimensions: 1

In [2]:
# 2D Array (Matrix)
mat = np.array([[1, 2, 3], [4, 5, 6]])

print('\nArray:\n', mat)
print('Shape:', mat.shape)
print('Size:', mat.size)
print('Data type:', mat.dtype)
print('Number of dimensions:', mat.ndim)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data type: int64
Number of dimensions: 2

In [3]:
# Convenience Constructors

zeros = np.zeros((2, 3))
print('\nZeros array\n', zeros)

ones = np.ones((3, 4))
print('\nOnes array\n', ones)

eye = np.eye(4)
print('\nIdentity matrix\n', eye)

arr_range = np.arange(0, 10, 2)
print('\nArange array\n', arr_range)

linspace = np.linspace(0, 1, 5)
print('\nLinspace array\n', linspace)

Zeros array
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones array
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Identity matrix
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Arange array
 [0 2 4 6 8]

Linspace array
 [0.   0.25 0.5  0.75 1.  ]

In [9]:
%pip install openpyxl

import pandas as pd

df = pd.read_excel('titanic_dataset.xlsx')

print('Data check:\n', df.head())

Requirement already satisfied: openpyxl in c:\Users\Administrator\Learnings\ai-training\.venv\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\Users\Administrator\Learnings\ai-training\.venv\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.
Data check:
    survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    str
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    str
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), str(7)
memory usage: 92.4 KB

In [11]:
print('Describe check:\n', df.describe())

print('\nShape check:\n', df.shape)

print('\nDescribe Check with round:\n', df.describe().round(2))

Describe check:
          survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

Shape check:
 (891, 15)

Describe Check with round:
        survived  pclass     age   sibsp   parch    fare
count    891.00  891.00  714.00  891.00  891.00  891.00
mean       0.38    2.31   29.70    0.52    0.38   32.20
std        0.49    0.84   14.53    1.10    0.81   49.69
min        0.00    1.00    0.42    0.00    0.00    0.00
25%        0.00    2.00   20.12    0.00    0.00    7.91
50%        0.00    3.00   28.00    0.00    0.00   14.45
75%        1.00    3.00   38.00    1.00    0.00   31.00
max        1.00    3.00   80.00    8.00    6.00  512.33

In [12]:
# Extension Task 1:

# 1. How many unique values does the 'embarked' column have?
print('Unique values in embarked column:', df['embarked'].nunique())

# 2. What is the most common value in the passenger class (pclass) column?
print('Most common value in pclass column:', df['pclass'].mode()[0])

Unique values in embarked column: 3
Most common value in pclass column: 3

In [13]:

# Extension Task 2:

# 1. Find all male passengers who paid a fare above 200 and survived.

male_high_fare_survived = df[
    (df['sex'] == 'male') &
    (df['fare'] > 200) &
    (df['survived'] == 1)
]

male_high_fare_survived

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True

In [14]:
# 2. Using iloc, extract the rows 100 to 109 and the last 3 columns.

df.iloc[100:110, -3:]

     embark_town alive  alone
100  Southampton    no   True
101  Southampton    no   True
102  Southampton    no  False
103  Southampton    no   True
104  Southampton    no  False
105  Southampton    no   True
106  Southampton   yes   True
107  Southampton   yes   True
108  Southampton    no   True
109   Queenstown   yes  False